require("plugins")
require("options")
require("keybinding")
require("plugins-config.nvim-tree")
require("plugins-config.bufferline")
require("plugins-config.lualine")
require("plugins-config.telescope")
require("plugins-config.treesitter")
require("plugins-config.marks")
require("plugins-config.toggleterm")
--require("plugins-config.symbolsoutline")
require("plugins-config.colorizer")
require("plugins-config.todo")
require("plugins-config.comment")
require("plugins-config.flash")

vim.cmd [[colorscheme PaperColor]]
